import "./styles.css";
import { APP_VERSION, MODEL_OPTIONS, QUALITY_PRESETS } from "./config.js";
import { PaddleOcrEngine, formatRuntimeDetails } from "./ocr-engine.js";
import { prepareImage } from "./image-tools.js";
import { renderComparison, renderFieldEditor, renderPreview } from "./render.js";
import { applyManualValue, autoSelectProfile, extractProfileFields, loadProfiles } from "./profile-engine.js";
import { compareExtractions } from "./comparison.js";
import { clearRecords, loadRecords, saveRecord } from "./storage.js";
import { exportRecords } from "./excel-export.js";
import { formatMilliseconds, safeError, serializableResult } from "./utils.js";

const engine=new PaddleOcrEngine();let profiles=[];let records=loadRecords();let comparison=null;
const slots={product:createSlot("product"),vda:createSlot("vda")};
const el=id=>document.getElementById(id);
el("version").textContent=`v${APP_VERSION}`;
setupOptions();setupSlot("product");setupSlot("vda");setupActions();renderAll();
Promise.all([loadProfiles().then(p=>{profiles=p;populateProfiles();}),initializeEngine()]).catch(()=>{});

function createSlot(key){return{key,file:null,prepared:null,result:null,wallMs:null,error:"",state:"empty",profile:null,extraction:null,manual:false};}
function setupOptions(){for(const m of Object.values(MODEL_OPTIONS))el("modelSelect").append(new Option(m.label,m.key));for(const p of Object.values(QUALITY_PRESETS))el("qualitySelect").append(new Option(p.label,p.key));el("modelSelect").value="standard";el("qualitySelect").value="balanced";}
function setupSlot(key){el(`${key}Input`).addEventListener("change",async e=>{const f=e.target.files?.[0];e.target.value="";if(f)await loadFile(key,f);});el(`${key}Profile`).addEventListener("change",()=>selectProfile(key,el(`${key}Profile`).value));}
function setupActions(){el("initializeButton").onclick=()=>initializeEngine(true);el("analyzeAllButton").onclick=analyzeAll;el("saveButton").onclick=storeCurrent;el("excelButton").onclick=()=>exportRecords(records);el("clearButton").onclick=()=>{if(confirm("Lokales Protokoll wirklich leeren?")){records=clearRecords();renderLog();}};el("debugButton").onclick=exportDebug;}
function populateProfiles(){for(const key of ["product","vda"]){const select=el(`${key}Profile`);select.replaceChildren(new Option("Automatisch",""));profiles.filter(p=>p.role===key).forEach(p=>select.append(new Option(p.name,p.id)));}}
async function initializeEngine(force=false){if(!force&&engine.ready)return true;setEngineStatus("PaddleOCR wird vorbereitet …","wait");try{const info=await engine.initialize("standard",m=>setEngineStatus(m,"wait"),force);setEngineStatus(`PaddleOCR bereit · ${info.mode}`,"ok");el("engineDetails").textContent=`Initialisierung ${formatMilliseconds(info.initMs)} · ${formatRuntimeDetails(info.summary)}`;return true;}catch(e){setEngineStatus(`PaddleOCR nicht bereit: ${safeError(e)}`,"bad");return false;}}
async function loadFile(key,file){const s=slots[key];Object.assign(s,{file,result:null,extraction:null,error:"",state:"preparing",manual:false});renderSlot(key);try{s.prepared=await prepareImage(file,QUALITY_PRESETS.balanced.maxImageSide);s.state="ready";renderSlot(key);await analyzeSlot(key);}catch(e){s.error=safeError(e);s.state="error";renderSlot(key);}}
async function analyzeSlot(key){const s=slots[key];if(!s.prepared||!(await initializeEngine()))return;s.state="analyzing";renderSlot(key);try{const p=QUALITY_PRESETS.balanced;const out=await engine.predict(s.prepared.canvas,{textDetLimitSideLen:p.textDetLimitSideLen,textDetLimitType:"min",textDetMaxSideLimit:2400,textDetThresh:.25,textDetBoxThresh:p.textDetBoxThresh,textDetUnclipRatio:1.55,textRecScoreThresh:p.textRecScoreThresh});s.result=out.result;s.wallMs=out.wallMs;s.state="done";setEngineStatus(`PaddleOCR bereit · ${out.mode}`,"ok");const metrics=out.result?.metrics||{};el("engineDetails").textContent=[formatRuntimeDetails(engine.summary,out.runtime),Number.isFinite(metrics.detMs)?`Detektion ${formatMilliseconds(metrics.detMs)}`:"",Number.isFinite(metrics.recMs)?`Erkennung ${formatMilliseconds(metrics.recMs)}`:""].filter(Boolean).join(" · ");resolveProfile(key);}catch(e){s.error=safeError(e);s.state="error";}renderAll();}
async function analyzeAll(){for(const k of ["product","vda"])if(slots[k].prepared)await analyzeSlot(k);}
function resolveProfile(key){const s=slots[key];if(!s.result)return;let profile=s.profile;if(!profile){const match=autoSelectProfile(s.result.items,profiles,key);profile=match?.profile||null;}s.profile=profile;s.extraction=profile?extractProfileFields(s.result.items,profile,s.result.image):null;el(`${key}Profile`).value=profile?.id||"";comparison=slots.product.extraction&&slots.vda.extraction?compareExtractions(slots.product.extraction,slots.vda.extraction):null;}
function selectProfile(key,id){const s=slots[key];s.profile=profiles.find(p=>p.id===id)||null;if(s.result){s.extraction=s.profile?extractProfileFields(s.result.items,s.profile,s.result.image):null;comparison=slots.product.extraction&&slots.vda.extraction?compareExtractions(slots.product.extraction,slots.vda.extraction):null;}renderAll();}
function editField(key,field,value){const s=slots[key];applyManualValue(s.extraction,field,value);s.manual=true;comparison=slots.product.extraction&&slots.vda.extraction?compareExtractions(slots.product.extraction,slots.vda.extraction):null;renderAll();}
function renderAll(){renderSlot("product");renderSlot("vda");renderComparison(el("comparison"),comparison);renderLog();el("saveButton").disabled=!comparison;el("excelButton").disabled=!records.length;}
function renderSlot(key){const s=slots[key];renderPreview(el(`${key}Preview`),s.prepared,s.extraction?.overlays||[]);const st=el(`${key}Status`);if(s.state==="analyzing"){st.textContent="PaddleOCR analysiert …";st.className="slot-status wait";}else if(s.state==="error"){st.textContent=`Fehler: ${s.error}`;st.className="slot-status bad";}else if(s.state==="done"){st.textContent=`${formatMilliseconds(s.wallMs)} · ${s.result?.items?.length||0} Textzeilen · ${s.profile?.name||"Profil nicht erkannt"}${s.extraction?.warning?` · ${s.extraction.warning}`:""}`;st.className=`slot-status ${s.profile?"ok":"warn"}`;}else{st.textContent=s.prepared?"Bild vorbereitet":"Noch kein Bild";st.className="slot-status";}renderFieldEditor(el(`${key}Fields`),s.extraction,(f,v)=>editField(key,f,v));}
function storeCurrent(){if(!comparison)return;const rec={timestamp:new Date().toISOString(),result:comparison.message,productProfile:slots.product.profile?.name||"",vdaProfile:slots.vda.profile?.name||"",product:values(slots.product.extraction),vda:values(slots.vda.extraction),manual:slots.product.manual||slots.vda.manual};records=saveRecord(rec);renderAll();}
function values(e){const o={};for(const [k,v] of Object.entries(e?.fields||{}))o[k]=v.value||"";return o;}
function renderLog(){el("logCount").textContent=`${records.length} Datensätze`;const body=el("logBody");body.replaceChildren();records.slice(0,30).forEach(r=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${new Date(r.timestamp).toLocaleString()}</td><td>${r.product.batch||"–"}</td><td>${r.product.drum_number||"–"}</td><td>${r.vda.batch||"–"}</td><td>${r.result}</td>`;body.append(tr);});}
function exportDebug(){const payload={exportedAt:new Date().toISOString(),appVersion:APP_VERSION,product:debugSlot(slots.product),vda:debugSlot(slots.vda),comparison};download(JSON.stringify(payload,null,2),`labelcheck-debug-${Date.now()}.json`,`application/json`);}
function debugSlot(s){return{profile:s.profile,extraction:s.extraction,result:serializableResult(s.result),wallMs:s.wallMs};}
function download(content,name,type){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function setEngineStatus(t,c){el("engineBadge").textContent=t;el("engineBadge").className=`engine-badge ${c}`;}
